config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :users, only: [:new, :create, :show, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, :category, :price, :description, :user_id, presence: true
    validates :category, inclusion: { in: %w(Automotive Books Electronics Handmade Home Outdoors Tools Games Clothing),
    message: "%{value} is not a valid category for a product!" }
    validate :check_name_length
    
    belongs_to :user

    def check_name_length
        unless name.length >= 2
            errors[:name] << "is too short, must be longer than two or more characters"
        end
    end
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
    include BCrypt
    validates :username, :password_digest, :session_token, :phone_number, :email, presence: true
    validates :password, length: { minimum: 6, allow_nil: true }
    after_initialize :ensure_session_token
    attr_reader :password

    has_many :products, dependent: :destroy

    # generates a random session token
    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    # calls g random and resets a random token to @session_token
    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save!
        self.session_token
    end

    # overrides the password setter method so that it BCrypts the input and
    # gets stored in the @password_digest
    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    # verifies whether or not password input matches with @password_digest 
    # BCrypted equivalent
    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    # finds the user given inputs username and password
    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    # validation method to call g random if @session_token is not set
    private
    def ensure_session_token
        # we must be sure to use the ||= operator instead of = or ||, otherwise
        # we will end up with a new session token every time we create
        # a new instance of the User class. This includes finding it in the DB!
        self.session_token ||= self.class.generate_session_token
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

  # to be able to use helper method on views
  helper_method :current_user

  # saves the user object to a variable and saves session on cookie
  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  # returns the current user object or finds it by the session token stored
  # after login!(user) you can safely use current_user()
  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Product.all
        render :index
    end
    
    # NEEDS WORK
    def show
        @product = Product.find_by(id: params[:id])
        if @product
            render :show
        else 
            redirect_to products_url
        end
    end

    def new
        render :new
    end

    def create
        @product = current_user.products.new(product_params)
        if @product.save
            redirect_to user_url(current_user)
        else
            flash.now[:errors] = @product.errors.full_messages
            render :new
        end
    end

    # NEEDS WORK
    def edit
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end

    # NEEDS WORK
    def update
        @cat = Cat.find_by(id: params[:id])
        if @cat.update_attributes(cat_params)
            redirect_to cat_url(@cat)
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find_by(id: params[:id])
        @product.destroy
        redirect_to user_url(current_user)
    end

    private
    def product_params
        params.require(:product).permit(:name, :category, :price, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        user = User.find_by_credentials(
        params[:user][:username],
        params[:user][:password]
        )

        if user.nil?
            flash.now[:errors] = ["Incorrect username and/or password"]
            render :new
        else
            login!(user)
            session[:session_token] = current_user.try(:reset_session_token!)
            redirect_to user_url(current_user)
        end
    end

    def destroy
        current_user.try(:reset_session_token!)
        session[:session_token] = nil
        redirect_to products_url
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:username, :password, :email, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
   <%= error %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Liquidation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text&display=swap" rel="stylesheet">  
    <script src="https://kit.fontawesome.com/bc74374db4.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="main-nav">

      <nav class="left-nav">
        <ul>
          <li><a href="<%= products_url %>">Liquidation</a></li>
        </ul>
      </nav>

      <nav class="right-nav">
        <ul>
          <li><a href="#">FAQ</a></li>
          <li><a href="#">About</a></li>
          <% if !current_user.nil? %>
              <li>
                <i class="fas fa-user-circle"></i> 
                <a href="<%= user_url(current_user) %>"><%= current_user.username %></a>
              </li>
              <li>
                <form action="<%= session_url %>" method="POST">
                  <input type="hidden"
                        name="authenticity_token"
                        value="<%= form_authenticity_token %>">
                  <input type="hidden" value="delete" name="_method" />
                  <input type="submit" value="Logout" />
                </form>
              </li>
          <% else %>
              <li><a href="<%= new_session_url %>">Log in</a></li>
              <li><a href="<%= new_user_url %>">Sign up</a></li>
          <% end %>
        </ul>
      </nav>

    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

<!--
<div class="header-nav-search">
  <input type="text" name="" placeholder="type to search">
  <div><a href="#">search</a></div>
</div>
-->

app/views/products/index.html.erb
<header class="secundary-nav">
    <nav>
        <ul>
            <li>
                <select>
                    <option disabled selected>-- Category --</option>
                    <option value="Automotive">Automotive</option>
                    <option value="Books">Books</option>
                    <option value="Electronics">Electronics</option>
                    <option value="Handmade">Handmade</option>
                    <option value="Home">Home</option>
                    <option value="Outdoors">Outdoors</option>
                    <option value="Tools">Tools</option>
                    <option value="Games">Games</option>
                    <option value="Clothing">Clothing</option>
                </select>
            </li>
            <li>
                <select>
                    <option disabled selected>-- Price range --</option>
                    <option value="low">0-$10</option>
                    <option value="Books">$10-$50</option>
                    <option value="Electronics">$50-$200</option>
                    <option value="Handmade">$200-$1000</option>
                    <option value="Home">$1000-$4000</option>
                    <option value="Outdoors">$4000-$10000</option>
                    <option value="Tools">$10000-$50000</option>
                </select>
            </li>
            <li>
                <input type="text" placeholder="Search ..." name="" id="">
            </li>
        </ul>
    </nav>
</header>

<div class="card-wrapper">
    <% @products.each do |product| %>
        <div class="card">
            <a href="<%= product_url(product) %>">
                <img class="card-image" src="https://picsum.photos/200/300" alt="">
                <div class="card-body">
                    <div class="card-body-title"><%= product.name %></div>
                    <div class="card-body-price">$ <%= product.price %></div>
                    <ul class="card-body-options">
                        <li><i class="far fa-heart"></i></li>
                        <li><i class="fas fa-phone"></i></li>
                        <li><i class="fas fa-ellipsis-v"></i></li>
                    </ul>
                </div>
            </a>
        </div>
    <% end %>
</div>

app/views/products/new.html.erb
<form class="liq-form" action="/products" method="post">
    <h1>Create new offer</h1>
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <label for="name">Name</label>
    <input id="name" type="text" name="product[name]" placeholder="Name">
    <br>
    <label for="category">Category</label>
    <select name="product[category]" id="category">
        <option disabled selected>-- Select a category --</option>
        <option value="Automotive">Automotive</option>
        <option value="Books">Books</option>
        <option value="Electronics">Electronics</option>
        <option value="Handmade">Handmade</option>
        <option value="Home">Home</option>
        <option value="Outdoors">Outdoors</option>
        <option value="Tools">Tools</option>
        <option value="Games">Games</option>
        <option value="Clothing">Clothing</option>
    </select>
    <br>
    <label for="price">Price</label>
    <input type="text" name="product[price]" id="price" placeholder="Name">
    <br>
    <label for="description">Description</label>
    <textarea name="product[description]" id="description" rows="5" placeholder="Add a description..."></textarea>
    <br>
    <input class="liq-button" type="submit" value="create offer">

</form>

app/views/products/show.html.erb
<div class="section group">
    <div class="col span_6_of_12">
        <div><img src="https://picsum.photos/500" alt="" class="image-show"></div>
    </div>

    <div class="col span_6_of_12 liq-product-display-description">
        <h2><%= @product.name %></h2>
        <ul>
            <li>$ <%= @product.price %></li>
            <li>Category: <%= @product.category %></li>
            <li>Seller: <%= @product.user.username %></li>
        </ul>
        <br>
        <br>
        <hr>
        <ul>
            <li><i class="fas fa-phone"></i> <%= @product.user.phone_number %></li>
            <li><i class="far fa-heart"></i> Add to likes</li>
            <li><i class="far fa-square"></i> Another option</li>
            <li><i class="far fa-flag"></i> Report</li>
        </ul>
    </div>
</div>

<div class="section group">
    <div class="col span_6_of_12">
        <h2>Description</h2>
        <div><%= @product.description %></div>
    </div>
</div>

<hr>
<br>
<br>

<h2>Related products</h2>

<div class="card-wrapper">
    <% 3.times do %>
        <div class="card">
            <a href="<%= product_url(@product) %>">
                <img class="card-image" src="https://picsum.photos/200/300" alt="">
                <div class="card-body">
                    <div class="card-body-title"><%= @product.name %></div>
                    <div class="card-body-price">$ <%= @product.price %></div>
                    <ul class="card-body-options">
                        <li><i class="far fa-heart"></i></li>
                        <li><i class="fas fa-phone"></i></li>
                        <li><i class="fas fa-ellipsis-v"></i></li>
                    </ul>
                </div>
            </a>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1>TO DO</h1>

app/views/users/new.html.erb
<form class="liq-form" action="<%= users_url %>" method="post">
  <h1>Sign up</h1>
  <input
     name="_method"
     type="hidden"
     value="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text" 
     placeholder="Enter username">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password"
     placeholder="Enter password">
  <br>

  <label for="user_email">Email</label>
  <input
     id="user_email"
     name="user[email]"
     type="text"
     placeholder="Enter email">
  <br>

  <label for="user_phone_number">Phone Number</label>
  <input
     id="user_phone_number"
     name="user[phone_number]"
     type="text"
     placeholder="Enter contact number">
  <br>

    <ul>
        <li>Agreed to all <a href="#">Terms and conditions</a></li>
    </ul>
  <input class="liq-button" type="submit" value="Sign up">
</form>

app/views/users/show.html.erb
<div class="section group">
    <div class="col span_4_of_12">
        <img class="profile-pic" src="https://picsum.photos/100" alt="">
    </div>
    <div class="col span_4_of_12">
        <ul class="user-show-ul-flex">
            <li><h2>My account </h2></li>
            <li><a href="<%= edit_user_url(current_user) %>">Edit</a></li>
        </ul>
        <ul>
            <li>Logged in as: <%=current_user.username %></li>
            <li>Email: <%=current_user.email %></li>
            <li>Phone Number: <%=current_user.phone_number %></li>
        </ul>
    </div>
</div>

<ul class="user-show-ul-flex">
    <li><h2>My products </h2></li>
    <li><a href="<%= new_product_url %>"> New</a></li>
</ul>

<div class="card-wrapper">
    <% current_user.products.each do |product| %>
        <div class="card">
            <a href="<%= product_url(product) %>">
                <img class="card-image" src="https://picsum.photos/200/300" alt="">
            </a>
            <div class="card-body">
                <div class="card-body-title"><%= product.name %></div>
                <div class="card-body-price">$<%= product.price %></div>
                <ul class="card-body-options">
                    <li><a href="<%= edit_product_url(product) %>">Edit</a></li>
                    <li>
                        <form action="<%= product_url(product) %>" method="POST">
                            <input type="hidden"
                                    name="authenticity_token"
                                    value="<%= form_authenticity_token %>">
                            <input type="hidden" value="delete" name="_method" />
                            <input type="submit" value="Delete" />
                        </form>   
                    </li>
                    <li><i class="far fa-heart"></i></li>
                    <li><i class="fas fa-phone"></i></li>
                    <li><i class="fas fa-ellipsis-v"></i></li>
                </ul>
            </div>
        </div>
    <% end %>
</div>

<hr>
<br>
<br>

<h2>My wish list</h2>

<div class="card-wrapper">
    <% current_user.products.each do |product| %>
        <div class="card">
            <a href="<%= product_url(product) %>">
                <img class="card-image" src="https://picsum.photos/200/300" alt="">
            </a>
            <div class="card-body">
                <div class="card-body-title"><%= product.name %></div>
                <div class="card-body-price">$<%= product.price %></div>
                <ul class="card-body-options">
                    <li><i class="far fa-heart"></i></li>
                    <li><i class="fas fa-phone"></i></li>
                    <li><i class="fas fa-ellipsis-v"></i></li>
                </ul>
            </div>
        </div>
    <% end %>
</div>